"""Deterministic Stable 1.0 RC freeze construction and drift verification."""

from __future__ import annotations

import copy
import os
import platform
import re
import subprocess
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit

from cryptad_certification.io import read_json, write_json
from cryptad_certification.models import RunContext
from cryptad_certification.schema_validation import validate_schema

from .content_profile_selection import select_trust_social_v1
from .stable_1_0_rc_core import (
    CONTENT_PROFILE_IDS,
    DIGEST_RE,
    FIRST_PARTY_APP_IDS,
    FREEZE_EXCEPTIONS_KIND,
    FREEZE_EXCEPTIONS_SCHEMA,
    FREEZE_KIND,
    SAME_RUN_INPUT_KEYS,
    SCHEMA_VERSION,
    STABLE_MILESTONE,
    TOOL_NAME,
    TOOL_VERSION,
    LoadedInput,
    SourceIdentity,
    ValidationState,
    all_unique,
    canonical_json,
    evidence_by_id,
    file_digest,
    parse_timestamp,
    placeholder_findings,
    semantic_digest,
)

FREEZE_SECTIONS = (
    "candidate",
    "platformApi",
    "stableCatalog",
    "firstPartyApps",
    "contentFormatProfiles",
    "limitationsAndPolicy",
    "acceptedFreezeExceptions",
)
EXCEPTION_TARGET_SECTIONS = FREEZE_SECTIONS[:-1]
PRODUCER_IDENTITY_KIND = "stable-1.0-rc-producer-identity"
VOLATILE_PRODUCER_FIELDS = frozenset(
    {
        "durationMs",
        "duration_ms",
        "elapsedMs",
        "elapsed_ms",
        "generatedAt",
        "gitBranch",
        "githubActions",
        "githubRef",
        "githubRunAttempt",
        "githubRunId",
        "githubSha",
        "githubWorkflow",
        "runnerOs",
        "startedAt",
        "stderr_tail",
        "stdout_tail",
    }
)
STABLE_READINESS_SAME_RUN_REFERENCES = {
    "appPlatformSummary": "appPlatform",
    "ecosystemMatrix": "ecosystemMatrix",
    "goNoGoSummary": "goNoGo",
    "productionBetaSummary": "productionBeta",
    "releaseCertificationSummary": "releaseCertification",
}
TEMPORARY_WORKDIR_PATH_RE = re.compile(
    r"<workdir>[/\\](cryptad-[A-Za-z0-9_.-]*?)-[a-z0-9_]{8}(?=[/\\]|$)"
)
NON_WAIVABLE_EXCEPTION_TARGETS = {
    "platformApi": frozenset(
        {
            "baselineName",
            "baselineContractVersion",
            "baselineDigest",
            "stableCapabilityCount",
            "stableEndpointCount",
            "stableBreakingChangeVerification",
        }
    ),
    "stableCatalog": frozenset({"channel"}),
}


def producer_identity_digest(
    loaded: LoadedInput,
    referenced_producers: dict[str, str] | None = None,
) -> str:
    """Digest one same-run producer after removing execution-only volatility.

    Exact file digests remain authoritative for externally supplied release evidence. Same-run
    producers are regenerated by every Stable RC invocation, so timestamps, command output tails,
    and timings cannot be part of their frozen identity. Stable-readiness input hashes for other
    same-run producers are replaced with those producers' semantic identities rather than dropped.
    """

    if loaded.key not in SAME_RUN_INPUT_KEYS:
        return loaded.digest
    normalized = _normalize_producer_value(
        loaded.value,
        loaded.key,
        referenced_producers or {},
    )
    return semantic_digest(
        {
            "schemaVersion": 1,
            "kind": PRODUCER_IDENTITY_KIND,
            "producer": loaded.key,
            "summary": normalized,
        }
    )


def _normalize_producer_value(
    value: Any,
    producer: str,
    referenced_producers: dict[str, str],
    path: tuple[str, ...] = (),
) -> Any:
    if isinstance(value, dict):
        normalized: dict[str, Any] = {}
        for key, child in value.items():
            if key in VOLATILE_PRODUCER_FIELDS:
                continue
            reference = (
                STABLE_READINESS_SAME_RUN_REFERENCES.get(path[-1])
                if producer == "stableReadiness"
                and key == "sha256"
                and len(path) == 2
                and path[0] == "inputs"
                else None
            )
            if reference is not None and reference in referenced_producers:
                normalized[key] = referenced_producers[reference]
                continue
            normalized[key] = _normalize_producer_value(
                child,
                producer,
                referenced_producers,
                (*path, key),
            )
        return normalized
    if isinstance(value, list):
        return [
            _normalize_producer_value(child, producer, referenced_producers, path)
            for child in value
        ]
    if isinstance(value, str):
        return TEMPORARY_WORKDIR_PATH_RE.sub(
            lambda match: f"<workdir>/{match.group(1)}-<temporary>",
            value,
        )
    return value


def producer_identity_digests(inputs: dict[str, LoadedInput]) -> dict[str, str]:
    """Build deterministic identities for the complete same-run producer graph."""

    missing = [key for key in SAME_RUN_INPUT_KEYS if key not in inputs]
    if missing:
        raise ValueError("same-run producer inputs are missing: " + ", ".join(missing))
    identities = {
        key: producer_identity_digest(inputs[key])
        for key in SAME_RUN_INPUT_KEYS
        if key != "stableReadiness"
    }
    identities["stableReadiness"] = producer_identity_digest(
        inputs["stableReadiness"],
        identities,
    )
    return identities


def parse_properties(path: Path) -> dict[str, str]:
    """Parse the strict single-line property artifacts emitted by Cryptad tooling."""

    if path.is_symlink() or not path.is_file():
        raise ValueError(f"required properties artifact is missing or unsafe: {path.name}")
    result: dict[str, str] = {}
    for line_number, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        key, separator, value = line.partition("=")
        if not separator or not key.strip():
            raise ValueError(f"malformed properties line {line_number} in {path.name}")
        key = key.strip()
        if key in result:
            raise ValueError(f"duplicate property {key} in {path.name}")
        result[key] = value.strip()
    return result


def production_native_root(production_envelope: Path) -> Path:
    """Resolve the established production-beta native artifact directory beside its envelope."""

    root = production_envelope.parent / "artifacts" / "legacy"
    if root.is_symlink() or not root.is_dir():
        raise ValueError("production-beta native artifact directory is missing or unsafe")
    return root.resolve()


def safe_artifact(root: Path, relative: str, *, directory: bool = False) -> Path:
    """Resolve one regular artifact below a trusted production native root."""

    candidate = root / relative
    current = root
    for part in Path(relative).parts:
        current /= part
        if current.is_symlink():
            raise ValueError(f"production artifact path contains a symlink: {relative}")
    resolved = candidate.resolve()
    try:
        resolved.relative_to(root.resolve())
    except ValueError as exc:
        raise ValueError(f"production artifact escapes its root: {relative}") from exc
    valid = resolved.is_dir() if directory else resolved.is_file()
    if not valid:
        raise ValueError(f"required production artifact is missing: {relative}")
    return resolved


def find_crypta_app(native_root: Path) -> Path:
    """Return the candidate-built crypta-app launcher copied by production-beta execution."""

    windows = platform.system() == "Windows"
    name = "crypta-app.bat" if windows else "crypta-app"
    candidate = safe_artifact(native_root, f"build/crypta-app-launcher/bin/{name}")
    if not windows and not os.access(candidate, os.X_OK):
        raise ValueError("candidate-built POSIX crypta-app launcher is not executable")
    return candidate


def run_crypta_app(cli: Path, arguments: list[str]) -> None:
    """Run one bounded offline candidate-built crypta-app operation."""

    result = subprocess.run(
        [str(cli), *arguments],
        check=False,
        capture_output=True,
        text=True,
        timeout=300,
    )
    if result.returncode != 0:
        raise ValueError(f"candidate-built crypta-app operation failed: {' '.join(arguments[:2])}")


def build_platform_api_freeze(
    context: RunContext,
    native_root: Path,
    output_root: Path,
    state: ValidationState,
) -> tuple[dict[str, Any], Path, Path]:
    """Generate and verify the current contract against the checked-in Stable 1.0 baseline."""

    baseline_path = safe_artifact(
        context.workspace_root,
        "docs/platform-api/contracts/platform-api-1.0-baseline.json",
    )
    policy_path = safe_artifact(
        context.workspace_root,
        "docs/platform-api-compatibility-support-window.md",
    )
    current_path = output_root / "platform-api-current-contract.json"
    diff_path = output_root / "platform-api-stable-diff.json"
    cli = find_crypta_app(native_root)
    run_crypta_app(cli, ["api", "snapshot", "--output", str(current_path)])
    try:
        run_crypta_app(
            cli,
            [
                "api",
                "diff",
                "--previous",
                str(baseline_path),
                "--current",
                str(current_path),
                "--production-beta",
                "--output",
                str(diff_path),
            ],
        )
    except ValueError:
        state.block(
            "stable-1.0-rc.platform-api-breaking-change",
            "stable-1.0-rc.platform-api-freeze",
            "The generated candidate contract does not preserve the Stable Platform API 1.0 baseline.",
            "Restore compatibility or complete the established baseline evolution process.",
        )
        if not diff_path.is_file():
            write_json(diff_path, {"schemaVersion": 1, "ok": False, "findings": []})
    baseline = read_json(baseline_path)
    current = read_json(current_path)
    baseline_contract = baseline.get("contract") if isinstance(baseline, dict) else None
    current_contract = current.get("contract") if isinstance(current, dict) else None
    if not isinstance(baseline_contract, dict) or not isinstance(current_contract, dict):
        raise ValueError("Platform API contract snapshot is malformed")
    stable = current_contract.get("stableBaseline")
    baseline_stable = baseline_contract.get("stableBaseline")
    if not isinstance(stable, dict) or not isinstance(baseline_stable, dict):
        raise ValueError("current Platform API contract omits stableBaseline")
    stable_surface_matches = stable_surface_is_exact(baseline_stable, stable)
    if not stable_surface_matches:
        state.block(
            "stable-1.0-rc.platform-api-stable-surface-drift",
            "stable-1.0-rc.platform-api-freeze",
            "The generated Stable Platform API surface does not exactly match the authoritative 1.0 baseline.",
            "Restore the exact ordered Stable capability and endpoint surface before cutting the RC.",
        )
    capabilities = current_contract.get("capabilities")
    endpoints = current_contract.get("endpoints")
    if not isinstance(capabilities, list) or not isinstance(endpoints, list):
        raise ValueError("current Platform API contract capability or endpoint list is malformed")
    experimental_capabilities = sum(
        1 for row in capabilities if isinstance(row, dict) and row.get("stability") == "experimental"
    )
    experimental_endpoints = sum(
        1 for row in endpoints if isinstance(row, dict) and row.get("stability") == "experimental"
    )
    diff = read_json(diff_path)
    return (
        {
            "baselineName": stable.get("name"),
            "baselineContractVersion": stable.get("contractVersion"),
            "baselineDigest": file_digest(baseline_path),
            "currentContractVersion": current_contract.get("contractVersion"),
            "currentContractDigest": file_digest(current_path),
            "compatibilityWindowPolicyDigest": file_digest(policy_path),
            "stableCapabilityCount": stable.get("capabilityCount"),
            "stableEndpointCount": stable.get("endpointCount"),
            "experimentalCapabilityCount": experimental_capabilities,
            "experimentalEndpointCount": experimental_endpoints,
            "stableBreakingChangeVerification": (
                "pass"
                if stable_surface_matches and isinstance(diff, dict) and diff.get("ok") is True
                else "fail"
            ),
            "verificationReportDigest": file_digest(diff_path),
        },
        current_path,
        diff_path,
    )


def stable_surface_is_exact(baseline: Any, current: Any) -> bool:
    """Return whether generated Stable API membership exactly equals the frozen baseline."""

    return isinstance(baseline, dict) and canonical_json(baseline) == canonical_json(current)


def export_content_profiles(
    native_root: Path,
    output_root: Path,
    app_platform_summary: dict[str, Any],
    state: ValidationState,
) -> tuple[list[dict[str, Any]], Path]:
    """Export profile descriptors from the candidate-built authoritative Java registry."""

    export_path = output_root / "content-format-profiles.json"
    run_crypta_app(
        find_crypta_app(native_root),
        ["api", "content-formats", "--output", str(export_path)],
    )
    value = read_json(export_path)
    profiles = select_trust_social_v1(value)
    evidence = evidence_by_id(app_platform_summary).get(
        "app-platform.trust-social-content-format-profiles",
        {},
    )
    if evidence.get("status") not in {"pass", "passed", "success"}:
        state.block(
            "stable-1.0-rc.content-format-evidence",
            "stable-1.0-rc.content-format-freeze",
            "Content-format parser and validator compatibility evidence is missing or failing.",
            "Rerun app-platform validation against the authoritative profile registry.",
        )
    evidence_digest = semantic_digest(evidence)
    frozen: list[dict[str, Any]] = []
    for row in profiles:
        if not isinstance(row, dict):
            raise ValueError("content-format profile descriptor is malformed")
        version_policy = row.get("versionPolicy")
        if not isinstance(version_policy, dict):
            raise ValueError("content-format version policy is malformed")
        rules = {
            "canonicalizationKind": row.get("canonicalizationKind"),
            "versionPolicy": version_policy,
        }
        signature_rules = {
            "signed": row.get("signed"),
            "signingDomain": row.get("signingDomain"),
        }
        frozen.append(
            {
                "profileId": row.get("id"),
                "version": row.get("majorVersion"),
                "status": row.get("status"),
                "descriptorDigest": semantic_digest(row),
                "canonicalizationRulesDigest": semantic_digest(rules),
                "maximumSizePolicy": {
                    "documentBytes": row.get("maxDocumentBytes"),
                    "signedPayloadBytes": row.get("maxSignedPayloadBytes"),
                },
                "signaturePayloadRules": signature_rules,
                "parserValidatorCompatibilityEvidenceDigest": evidence_digest,
            }
        )
    return frozen, export_path


def _catalog_contract_record(value: Any, fields: tuple[str, ...]) -> dict[str, Any]:
    """Copy only schema-contracted fields from one protected catalog-operations record."""

    if not isinstance(value, dict):
        return {}
    return {field: copy.deepcopy(value.get(field)) for field in fields}


def _catalog_operations_freeze(catalog_operations: dict[str, Any]) -> dict[str, Any]:
    """Return the schema-contracted catalog operation and health snapshot."""

    health_fields = ("status", "signatureVerified", "revision", "digest")
    mirrors = catalog_operations.get("mirrors")
    return {
        "keyRotationStatus": _catalog_contract_record(
            catalog_operations.get("keyRotation"),
            ("status", "compromised"),
        ),
        "primaryHealth": _catalog_contract_record(
            catalog_operations.get("primary"),
            health_fields,
        ),
        "mirrorHealth": [
            _catalog_contract_record(
                mirror,
                (*health_fields, "transportFallbackOnly"),
            )
            for mirror in (mirrors if isinstance(mirrors, list) else [])
        ],
        "verifiedRollback": _catalog_contract_record(
            catalog_operations.get("rollback"),
            health_fields,
        ),
    }


def build_catalog_and_apps_freeze(
    native_root: Path,
    current_contract: Path,
    catalog_operations: dict[str, Any],
    output_root: Path,
    allowed_limitation_ids: set[str],
    state: ValidationState,
    production_signing: dict[str, Any] | None = None,
) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    """Freeze the exact signed stable catalog and its first-party app set."""

    catalog_path = safe_artifact(native_root, "catalog/first-party-catalog.properties")
    signature_path = safe_artifact(native_root, "catalog/cryptad-app-catalog.signature")
    signature_alias_path = safe_artifact(native_root, "catalog/first-party-catalog.sig")
    metadata_path = safe_artifact(native_root, "catalog/channel-metadata.json")
    maintenance_path = safe_artifact(native_root, "inputs/first-party-app-maintenance-policy.json")
    readiness_path = safe_artifact(native_root, "inputs/first-party-app-beta-readiness.json")
    catalog = parse_properties(catalog_path)
    signature = parse_properties(signature_path)
    metadata = read_json(metadata_path)
    maintenance = read_json(maintenance_path)
    readiness = read_json(readiness_path)
    if not all(isinstance(value, dict) for value in (metadata, maintenance, readiness)):
        raise ValueError("production catalog policy metadata is malformed")
    catalog_digest = file_digest(catalog_path)
    signature_digest = file_digest(signature_path)
    signature_alias_digest = file_digest(signature_alias_path)
    catalog_artifact_timestamp = catalog.get("catalog.generatedAt")
    if (
        parse_timestamp(catalog_artifact_timestamp) is None
        or parse_timestamp(catalog_artifact_timestamp)
        != parse_timestamp(catalog_operations.get("artifactTimestamp"))
    ):
        state.block(
            "stable-1.0-rc.catalog-operations-binding.artifactTimestamp",
            "stable-1.0-rc.catalog-freeze",
            "Protected catalog-operations artifactTimestamp does not match the signed catalog.",
            "Rebuild and sign the catalog with the protected frozen artifact timestamp.",
        )
    if signature_alias_path.read_bytes() != signature_path.read_bytes():
        state.block(
            "stable-1.0-rc.catalog-signature-alias",
            "stable-1.0-rc.catalog-freeze",
            "Catalog signature alias bytes differ from the canonical signature sidecar.",
            "Regenerate both sidecars from the exact signed catalog.",
        )
    channel = metadata.get("channel")
    ordered_ids = [item for item in catalog.get("catalog.entries", "").split(",") if item]
    if (
        channel != "stable"
        or metadata.get("nonProduction") is not False
        or metadata.get("signingProfile") != "production"
        or set(ordered_ids) != FIRST_PARTY_APP_IDS
        or len(ordered_ids) != len(FIRST_PARTY_APP_IDS)
        or not all_unique(ordered_ids)
    ):
        state.block(
            "stable-1.0-rc.stable-catalog-invariants",
            "stable-1.0-rc.catalog-freeze",
            "The signed catalog is not an exact production stable-channel first-party catalog.",
            "Regenerate the signed stable catalog with exactly the policy-required app set.",
        )
    catalog_key = signature.get("catalog.signature.key.id")
    edition = metadata.get("stableChannelEdition")
    comparisons = {
        "catalogId": catalog.get("catalog.id"),
        "channel": channel,
        "revision": edition,
        "catalogDigest": catalog_digest,
        "signatureDigest": signature_digest,
        "signingKeyId": catalog_key,
    }
    for key, actual in comparisons.items():
        if catalog_operations.get(key) != actual:
            state.block(
                f"stable-1.0-rc.catalog-operations-binding.{key}",
                "stable-1.0-rc.catalog-freeze",
                f"Protected catalog-operations {key} does not match the signed catalog artifact.",
                "Regenerate current-candidate catalog operations evidence from the signed stable catalog.",
            )
    for label, health in [
        ("primary", catalog_operations.get("primary")),
        *[
            (f"mirror[{index}]", row)
            for index, row in enumerate(catalog_operations.get("mirrors", []))
        ],
    ]:
        if not isinstance(health, dict):
            continue
        if health.get("digest") != catalog_digest or health.get("revision") != edition:
            state.block(
                f"stable-1.0-rc.catalog-health-binding.{label}",
                "stable-1.0-rc.catalog-freeze",
                f"Protected {label} health does not bind the frozen signed catalog revision.",
                "Fetch and verify the exact signed stable catalog from every configured source.",
            )
    catalog_version = _integer(catalog.get("catalog.version"))
    if catalog_version is None or catalog_version < 1:
        raise ValueError("signed stable catalog version is missing or invalid")
    apps = _build_first_party_apps(
        native_root,
        current_contract,
        output_root,
        ordered_ids,
        catalog,
        metadata,
        maintenance,
        readiness,
        allowed_limitation_ids,
        state,
        production_signing or {},
    )
    frozen_catalog = {
        "catalogId": catalog.get("catalog.id"),
        "channel": channel,
        "catalogVersion": catalog_version,
        "edition": edition,
        "revision": edition,
        "catalogDigest": catalog_digest,
        "signatureDigest": signature_digest,
        "signatureAliasDigest": signature_alias_digest,
        "catalogSigningKeyId": catalog_key,
        "artifactTimestamp": catalog_artifact_timestamp,
        **_catalog_operations_freeze(catalog_operations),
        "securityAdvisoryCount": catalog_operations.get("advisoryCount"),
        "denylistCount": catalog_operations.get("denylistCount"),
        "orderedEntries": [
            {"appId": app["appId"], "version": app["version"]} for app in apps
        ],
    }
    return frozen_catalog, apps


def _build_first_party_apps(
    native_root: Path,
    current_contract: Path,
    output_root: Path,
    ordered_ids: list[str],
    catalog: dict[str, str],
    channel_metadata: dict[str, Any],
    maintenance_policy: dict[str, Any],
    readiness_policy: dict[str, Any],
    allowed_limitation_ids: set[str],
    state: ValidationState,
    production_signing: dict[str, Any],
) -> list[dict[str, Any]]:
    metadata_rows = channel_metadata.get("apps") if isinstance(channel_metadata.get("apps"), list) else []
    metadata_ids = [row.get("appId") for row in metadata_rows if isinstance(row, dict)]
    metadata_apps = {
        row.get("appId"): row
        for row in metadata_rows
        if isinstance(row, dict) and isinstance(row.get("appId"), str)
    }
    maintenance_apps = maintenance_policy.get("apps") if isinstance(maintenance_policy.get("apps"), dict) else {}
    readiness_apps = readiness_policy.get("apps") if isinstance(readiness_policy.get("apps"), dict) else {}
    if (
        len(metadata_rows) != len(FIRST_PARTY_APP_IDS)
        or not all_unique(str(item) for item in metadata_ids)
        or set(metadata_apps) != FIRST_PARTY_APP_IDS
        or set(maintenance_apps) != FIRST_PARTY_APP_IDS
        or set(readiness_apps) != FIRST_PARTY_APP_IDS
    ):
        state.block(
            "stable-1.0-rc.first-party-set",
            "stable-1.0-rc.first-party-app-freeze",
            "Catalog, maintenance policy, and beta-readiness app sets are not identical.",
            "Regenerate complete first-party policy and signed catalog artifacts.",
        )
    cli = find_crypta_app(native_root)
    frozen: list[dict[str, Any]] = []
    for app_id in ordered_ids:
        prefix = f"app.{app_id}."
        app_summary = metadata_apps.get(app_id, {})
        version = str(catalog.get(prefix + "version") or app_summary.get("version") or "")
        bundle_relative = app_summary.get("artifact")
        if not isinstance(bundle_relative, str) or not bundle_relative:
            raise ValueError(f"catalog metadata omits bundle artifact for {app_id}")
        bundle_path = safe_artifact(native_root, bundle_relative)
        manifest_path = safe_artifact(native_root, f"build/staged-apps/{app_id}/cryptad-app.properties")
        bundle_signature_path = safe_artifact(native_root, f"build/staged-apps/{app_id}/cryptad-app.signature")
        receipt_path = safe_artifact(native_root, f"reviews/review-receipts/{app_id}-review-receipt.properties")
        manifest = parse_properties(manifest_path)
        bundle_signature = parse_properties(bundle_signature_path)
        receipt = parse_properties(receipt_path)
        report_path = output_root / f"{app_id}-api-compatibility.json"
        try:
            run_crypta_app(
                cli,
                [
                    "compat",
                    "verify",
                    "--bundle-dir",
                    str(manifest_path.parent),
                    "--contract",
                    str(current_contract),
                    "--strict",
                    "--json",
                    str(report_path),
                ],
            )
        except ValueError:
            state.block(
                f"stable-1.0-rc.app-api-compatibility.{app_id}",
                "stable-1.0-rc.first-party-app-freeze",
                f"First-party app {app_id} is incompatible with the candidate Platform API contract.",
                "Update and retest the app compatibility declaration before cutting the RC.",
            )
            if not report_path.is_file():
                write_json(report_path, {"schemaVersion": 1, "ok": False, "findings": []})
        report = read_json(report_path)
        app_policy = maintenance_apps.get(app_id) if isinstance(maintenance_apps.get(app_id), dict) else {}
        maintenance = app_policy.get("maintenance") if isinstance(app_policy.get("maintenance"), dict) else {}
        beta_row = readiness_apps.get(app_id) if isinstance(readiness_apps.get(app_id), dict) else {}
        beta = beta_row.get("betaReadiness") if isinstance(beta_row.get("betaReadiness"), dict) else {}
        permissions = sorted({item.strip() for item in manifest.get("app.permissions", "").split(",") if item.strip()})
        local_limitation: str | None = None
        if app_id == "trust-graph" and maintenance.get("supportLevel") == "local-rc":
            local_limitation = "stable-1.0.trust-graph-local-scope"
        elif app_id == "social-inbox" and maintenance.get("supportLevel") == "local-rc":
            local_limitation = "stable-1.0.social-inbox-no-legacy-protocol"
        if local_limitation is not None and local_limitation not in allowed_limitation_ids:
            state.block(
                f"stable-1.0-rc.local-rc-limitation.{app_id}",
                "stable-1.0-rc.first-party-app-freeze",
                f"First-party app {app_id} has local-rc status without its Stable limitation.",
                "Restore the reviewed limitation or do not include the local-rc app in Stable.",
            )
        expected_bundle_digest = "sha256:" + str(app_summary.get("sha256", "")).lower().removeprefix("sha256:")
        actual_bundle_digest = file_digest(bundle_path)
        if expected_bundle_digest != actual_bundle_digest:
            state.block(
                f"stable-1.0-rc.bundle-digest.{app_id}",
                "stable-1.0-rc.first-party-app-freeze",
                f"Bundle digest for {app_id} does not match channel metadata.",
                "Rebuild and re-sign the catalog from the exact bundle bytes.",
            )
        app_key_id = bundle_signature.get("signature.key.id")
        reviewer_key_id = receipt.get("review.receipt.reviewer.key.id")
        expected_app_key = production_signing.get("appKeyId")
        expected_reviewer_key = production_signing.get("reviewerKeyId")
        invariants = {
            "maintenance channel": app_policy.get("channel") == "stable",
            "channel metadata channel": app_summary.get("channel") == "stable",
            "catalog channel": catalog.get(prefix + "channel") == "stable",
            "support status": app_policy.get("supportStatus") == "supported",
            "non-production marker": app_summary.get("nonProduction") is False,
            "manifest app ID": manifest.get("app.id") == app_id,
            "manifest version": manifest.get("app.version") == version,
            "channel metadata version": str(app_summary.get("version")) == version,
            "bundle size": app_summary.get("sizeBytes") == bundle_path.stat().st_size,
            "bundle signing key": bool(app_key_id) and app_key_id == expected_app_key,
            "receipt bundle key": receipt.get("review.receipt.bundle.key.id") == app_key_id,
            "reviewer key": bool(reviewer_key_id) and reviewer_key_id == expected_reviewer_key,
            "beta readiness": beta.get("status") == "ready",
            "beta owner": isinstance(beta.get("owner"), str) and bool(beta.get("owner", "").strip()),
            "beta support metadata": beta.get("supportMetadata") == "required",
            "redacted diagnostics": beta.get("diagnostics") == "redacted-summary-only",
            "migration readiness": isinstance(beta.get("migrationDryRun"), str) and bool(beta.get("migrationDryRun")),
            "backup/restore readiness": isinstance(beta.get("backupRestore"), str) and bool(beta.get("backupRestore")),
        }
        deprecation = app_policy.get("deprecationStatus")
        replacement = manifest.get("app.replacement.id")
        invariants["deprecation policy"] = deprecation == "none" or (
            deprecation == "deprecated" and isinstance(replacement, str) and bool(replacement)
        )
        for invariant, passed in invariants.items():
            if not passed:
                state.block(
                    f"stable-1.0-rc.app-invariant.{app_id}.{invariant.replace(' ', '-')}",
                    "stable-1.0-rc.first-party-app-freeze",
                    f"First-party app {app_id} failed its {invariant} invariant.",
                    "Regenerate the production-signed app, review receipt, policy, and stable catalog entry.",
                )
        if (
            receipt.get("review.receipt.app.id") != app_id
            or receipt.get("review.receipt.app.version") != version
            or receipt.get("review.receipt.status") != "reviewed"
            or receipt.get("review.receipt.artifact.sha256") != actual_bundle_digest.removeprefix("sha256:")
        ):
            state.block(
                f"stable-1.0-rc.review-receipt.{app_id}",
                "stable-1.0-rc.first-party-app-freeze",
                f"Trusted review receipt for {app_id} does not bind the frozen app artifact.",
                "Issue and verify a trusted production review receipt for the exact bundle.",
            )
        production_values = {"manifest": manifest, "maintenance": maintenance, "catalog": {key: value for key, value in catalog.items() if key.startswith(prefix)}}
        if placeholder_findings(production_values):
            state.block(
                f"stable-1.0-rc.app-placeholder.{app_id}",
                "stable-1.0-rc.first-party-app-freeze",
                f"First-party app {app_id} contains placeholder production metadata.",
                "Replace example and REPLACE_ME values with real public support metadata.",
            )
        data_schema: int | str = "not-applicable"
        if "app.data.schema.current" in manifest:
            data_schema = _integer(manifest.get("app.data.schema.current"))
        frozen.append(
            {
                "appId": app_id,
                "version": version,
                "channel": app_policy.get("channel"),
                "supportStatus": app_policy.get("supportStatus"),
                "deprecationStatus": app_policy.get("deprecationStatus"),
                "supportLevel": maintenance.get("supportLevel"),
                "replacementAppId": manifest.get("app.replacement.id"),
                "bundleDigest": actual_bundle_digest,
                "bundleSizeBytes": bundle_path.stat().st_size,
                "appSigningKeyId": app_key_id,
                "reviewReceiptDigest": file_digest(receipt_path),
                "reviewerKeyId": reviewer_key_id,
                "manifestDigest": file_digest(manifest_path),
                "declaredPermissionSetDigest": semantic_digest(permissions),
                "targetApiStability": manifest.get("api.targetStability"),
                "apiCompatibilityResult": "pass" if isinstance(report, dict) and report.get("ok") is True else "fail",
                "apiCompatibilityEvidenceDigest": file_digest(report_path),
                "appDataSchemaVersion": data_schema,
                "migrationReadiness": beta.get("migrationDryRun"),
                "backupRestore": beta.get("backupRestore"),
                "betaReadinessEvidenceDigest": semantic_digest(beta_row),
                "supportMetadataDigest": semantic_digest(
                    {"maintenance": maintenance, "supportMetadata": beta.get("supportMetadata")}
                ),
                "supportUri": maintenance.get("supportUri"),
                "redactedDiagnosticsReadiness": beta.get("diagnostics"),
                "allowedStableLimitationId": local_limitation,
            }
        )
    return frozen


def build_limitations_freeze(
    readiness: dict[str, Any],
    policy_input: LoadedInput,
    known_input: LoadedInput,
    public_issues_input: LoadedInput,
    app_platform: dict[str, Any],
    security_digest: str,
    state: ValidationState,
) -> dict[str, Any]:
    """Freeze only PR-282-validated open allowed limitations and their policy bindings."""

    policy = policy_input.value
    allowed_categories = set(policy.get("allowedLimitationCategories", []))
    allowed = readiness.get("allowedLimitations")
    if not isinstance(allowed, list):
        raise ValueError("Stable readiness allowedLimitations is malformed")
    frozen_allowed: list[dict[str, Any]] = []
    seen: set[str] = set()
    for limitation in allowed:
        if not isinstance(limitation, dict):
            raise ValueError("Stable readiness allowed limitation is malformed")
        limitation_id = limitation.get("id")
        if not isinstance(limitation_id, str) or not limitation_id or limitation_id in seen:
            state.block(
                "stable-1.0-rc.allowed-limitation-identity",
                "stable-1.0-rc.limitations-freeze",
                "Allowed Stable limitations contain a missing or duplicate ID.",
                "Regenerate Stable readiness from the authoritative limitations file.",
            )
        seen.add(str(limitation_id))
        if (
            limitation.get("classification") != "allowed-for-stable-1.0"
            or limitation.get("status") != "open"
            or limitation.get("category") not in allowed_categories
            or not isinstance(limitation.get("boundedBy"), str)
            or not limitation.get("boundedBy", "").strip()
            or not isinstance(limitation.get("owner"), str)
            or not limitation.get("owner", "").strip()
        ):
            state.block(
                f"stable-1.0-rc.allowed-limitation.{limitation_id}",
                "stable-1.0-rc.limitations-freeze",
                f"Allowed limitation {limitation_id} is not policy-recognized, bounded, open, and owned.",
                "Correct the authoritative limitation record and regenerate Stable readiness.",
            )
        frozen_allowed.append(copy.deepcopy(limitation))
    evidence = evidence_by_id(app_platform)
    legacy_rows = {
        key: evidence.get(key, {})
        for key in (
            "legacy-plugin.migration-finalization",
            "legacy-admin.final-admin-surface",
        )
    }
    support_rows = {
        key: evidence.get(key, {})
        for key in (
            "public-beta.support-feedback-loop",
            "public-beta.security-reporting-handoff",
            "public-beta.release-notes-template",
        )
    }
    return {
        "stableReadinessPolicyDigest": policy_input.digest,
        "allowedLimitations": frozen_allowed,
        "allowedLimitationsDigest": semantic_digest(frozen_allowed),
        "allowedLimitationCount": len(frozen_allowed),
        "disallowedLimitationCount": readiness.get("disallowedLimitationCount"),
        "betaOnlyLimitationCount": 0,
        "publicBetaKnownIssuesDigest": public_issues_input.digest,
        "stableKnownLimitationsDigest": known_input.digest,
        "securityDrillSummaryDigest": security_digest,
        "legacyPluginAdminFreezeEvidenceDigest": semantic_digest(legacy_rows),
        "supportFeedbackReadinessEvidenceDigest": semantic_digest(support_rows),
    }


def assemble_freeze(
    *,
    context: RunContext,
    source: SourceIdentity,
    frozen_at: str,
    inputs: dict[str, LoadedInput],
    catalog_operations: LoadedInput,
    platform_api: dict[str, Any],
    stable_catalog: dict[str, Any],
    first_party_apps: list[dict[str, Any]],
    content_profiles: list[dict[str, Any]],
    limitations: dict[str, Any],
    accepted_exceptions: list[dict[str, Any]],
    production_distribution_digest: str,
) -> dict[str, Any]:
    """Assemble the canonical freeze object and attach its semantic content digest."""

    producer_digests = producer_identity_digests(inputs)
    freeze = {
        "schemaVersion": SCHEMA_VERSION,
        "kind": FREEZE_KIND,
        "stableMilestone": STABLE_MILESTONE,
        "frozenAt": frozen_at,
        "candidate": {
            "releaseId": context.manifest.release.release_id,
            "buildVersion": context.manifest.release.version,
            "sourceCommit": source.commit,
            "sourceRef": source.ref,
            "sourceProvenanceDigest": source.digest,
            "generationTool": TOOL_NAME,
            "generationToolVersion": TOOL_VERSION,
            "productionBetaSummaryDigest": producer_digests["productionBeta"],
            "productionDistributionDigest": production_distribution_digest,
            "stableReadinessSummaryDigest": producer_digests["stableReadiness"],
            "releaseCertificationSummaryDigest": producer_digests["releaseCertification"],
            "goNoGoSummaryDigest": producer_digests["goNoGo"],
            "ecosystemMatrixDigest": producer_digests["ecosystemMatrix"],
            "releaseHistoryDigest": inputs["releaseHistory"].digest,
            "previousCandidateDigest": inputs["previousCandidate"].digest,
            "liveNetworkDigest": inputs["liveNetwork"].digest,
            "multiNodeSoakDigest": inputs["multiNodeSoak"].digest,
            "networkScaleSoakDigest": inputs["networkScaleSoak"].digest,
            "securityDrillDigest": inputs["securityDrills"].digest,
            "thirdPartyIntakeDigest": inputs["thirdPartyIntake"].digest,
            "catalogOperationsDigest": catalog_operations.digest,
        },
        "platformApi": platform_api,
        "stableCatalog": stable_catalog,
        "firstPartyApps": first_party_apps,
        "contentFormatProfiles": content_profiles,
        "limitationsAndPolicy": limitations,
        "acceptedFreezeExceptions": accepted_exceptions,
    }
    freeze["contentDigest"] = freeze_content_digest(freeze)
    return freeze


def freeze_content_digest(freeze: dict[str, Any]) -> str:
    """Hash a freeze object while excluding only its self-referential contentDigest field."""

    content = copy.deepcopy(freeze)
    content.pop("contentDigest", None)
    return semantic_digest(content)


_SCHEMA_DIR = Path(__file__).resolve().parents[2] / "schemas"
_FREEZE_SCHEMA = _SCHEMA_DIR / "stable-1.0-rc-freeze-v1.schema.json"
_SUPPORTED_SCHEMA_KEYS = frozenset(
    {
        "$schema",
        "$id",
        "$ref",
        "$defs",
        "title",
        "type",
        "additionalProperties",
        "required",
        "properties",
        "const",
        "enum",
        "pattern",
        "minLength",
        "minimum",
        "minItems",
        "maxItems",
        "uniqueItems",
        "items",
        "oneOf",
        "format",
    }
)


def _json_equal(left: Any, right: Any) -> bool:
    if isinstance(left, bool) or isinstance(right, bool):
        return type(left) is type(right) and left == right
    return left == right


def _matches_schema_type(value: Any, expected: str) -> bool:
    return {
        "array": isinstance(value, list),
        "boolean": type(value) is bool,
        "integer": type(value) is int,
        "null": value is None,
        "object": isinstance(value, dict),
        "string": isinstance(value, str),
    }.get(expected, False)


def _schema_pointer(root: dict[str, Any], fragment: str) -> dict[str, Any]:
    current: Any = root
    if fragment and not fragment.startswith("/"):
        raise ValueError("schema reference fragment is malformed")
    for raw_part in fragment.lstrip("/").split("/") if fragment else []:
        part = raw_part.replace("~1", "/").replace("~0", "~")
        if not isinstance(current, dict) or part not in current:
            raise ValueError("schema reference does not resolve")
        current = current[part]
    if not isinstance(current, dict):
        raise ValueError("schema reference target is not an object")
    return current


def _resolve_schema_reference(
    reference: str,
    root_schema: dict[str, Any],
    cache: dict[str, dict[str, Any]],
) -> tuple[dict[str, Any], dict[str, Any]]:
    filename, marker, fragment = reference.partition("#")
    if not filename:
        return _schema_pointer(root_schema, fragment if marker else ""), root_schema
    relative = Path(filename)
    if relative.is_absolute() or ".." in relative.parts:
        raise ValueError("external schema reference is unsafe")
    target = _SCHEMA_DIR / relative
    if target.is_symlink() or not target.is_file():
        raise ValueError("external schema reference is missing or unsafe")
    resolved = target.resolve()
    try:
        resolved.relative_to(_SCHEMA_DIR.resolve())
    except ValueError as exc:
        raise ValueError("external schema reference escapes the schema directory") from exc
    key = resolved.as_posix()
    external = cache.get(key)
    if external is None:
        loaded = read_json(resolved)
        if not isinstance(loaded, dict):
            raise ValueError("external schema is malformed")
        external = loaded
        cache[key] = external
    return _schema_pointer(external, fragment if marker else ""), external


def _schema_errors(
    value: Any,
    schema: dict[str, Any],
    root_schema: dict[str, Any],
    path: str,
    cache: dict[str, dict[str, Any]],
) -> list[str]:
    unsupported = set(schema).difference(_SUPPORTED_SCHEMA_KEYS)
    if unsupported:
        return [f"{path} uses unsupported freeze schema constraints"]
    reference = schema.get("$ref")
    if isinstance(reference, str):
        try:
            resolved, resolved_root = _resolve_schema_reference(reference, root_schema, cache)
        except (OSError, ValueError):
            return [f"{path} references an unavailable freeze schema definition"]
        return _schema_errors(value, resolved, resolved_root, path, cache)
    one_of = schema.get("oneOf")
    if isinstance(one_of, list):
        matching = [
            branch
            for branch in one_of
            if isinstance(branch, dict)
            and not _schema_errors(value, branch, root_schema, path, cache)
        ]
        if len(matching) != 1:
            return [f"{path} does not match exactly one allowed freeze schema shape"]
    expected_type = schema.get("type")
    if isinstance(expected_type, str):
        allowed_types = [expected_type]
    elif isinstance(expected_type, list) and all(isinstance(item, str) for item in expected_type):
        allowed_types = expected_type
    else:
        allowed_types = []
    if allowed_types and not any(_matches_schema_type(value, item) for item in allowed_types):
        return [f"{path} has the wrong freeze schema type"]
    errors: list[str] = []
    if "const" in schema and not _json_equal(value, schema["const"]):
        errors.append(f"{path} does not match the required freeze schema constant")
    allowed_values = schema.get("enum")
    if isinstance(allowed_values, list) and not any(_json_equal(value, item) for item in allowed_values):
        errors.append(f"{path} is not an allowed freeze schema value")
    if isinstance(value, str):
        minimum_length = schema.get("minLength")
        if type(minimum_length) is int and len(value) < minimum_length:
            errors.append(f"{path} is shorter than the freeze schema minimum")
        pattern = schema.get("pattern")
        if isinstance(pattern, str) and re.search(pattern, value) is None:
            errors.append(f"{path} does not match the freeze schema pattern")
        value_format = schema.get("format")
        if value_format == "date-time" and parse_timestamp(value) is None:
            errors.append(f"{path} is not a valid freeze schema date-time")
        if value_format == "uri":
            parsed = urlsplit(value)
            if not parsed.scheme or any(character.isspace() for character in value):
                errors.append(f"{path} is not a valid freeze schema URI")
    if type(value) is int and type(schema.get("minimum")) is int and value < schema["minimum"]:
        errors.append(f"{path} is below the freeze schema minimum")
    if isinstance(value, dict):
        properties = schema.get("properties") if isinstance(schema.get("properties"), dict) else {}
        required = schema.get("required") if isinstance(schema.get("required"), list) else []
        for name in required:
            if isinstance(name, str) and name not in value:
                errors.append(f"{path} omits required field {name}")
        if schema.get("additionalProperties") is False:
            for name in sorted(set(value).difference(properties)):
                errors.append(f"{path} contains unknown field {name}")
        for name, child in value.items():
            child_schema = properties.get(name)
            if isinstance(child_schema, dict):
                errors.extend(_schema_errors(child, child_schema, root_schema, f"{path}.{name}", cache))
    if isinstance(value, list):
        minimum_items = schema.get("minItems")
        maximum_items = schema.get("maxItems")
        if type(minimum_items) is int and len(value) < minimum_items:
            errors.append(f"{path} has fewer items than the freeze schema minimum")
        if type(maximum_items) is int and len(value) > maximum_items:
            errors.append(f"{path} has more items than the freeze schema maximum")
        if schema.get("uniqueItems") is True:
            serialized = [canonical_json(item) for item in value]
            if len(serialized) != len(set(serialized)):
                errors.append(f"{path} contains duplicate freeze schema items")
        item_schema = schema.get("items")
        if isinstance(item_schema, dict):
            for index, item in enumerate(value):
                errors.extend(_schema_errors(item, item_schema, root_schema, f"{path}[{index}]", cache))
    return errors


def validate_freeze_shape(value: Any) -> list[str]:
    """Validate the complete freeze against the checked-in v1 schema and cross-field invariants."""

    if not isinstance(value, dict):
        return ["freeze must be a JSON object"]
    try:
        schema = read_json(_FREEZE_SCHEMA)
    except (OSError, ValueError):
        return ["freeze v1 schema is missing or malformed"]
    if not isinstance(schema, dict):
        return ["freeze v1 schema is missing or malformed"]
    errors = _schema_errors(value, schema, schema, "$", {})
    if value.get("contentDigest") != freeze_content_digest(value):
        errors.append("freeze contentDigest does not match canonical content")
    apps = value.get("firstPartyApps") if isinstance(value.get("firstPartyApps"), list) else []
    app_ids = [row.get("appId") for row in apps if isinstance(row, dict)]
    if len(app_ids) != len(FIRST_PARTY_APP_IDS) or set(app_ids) != FIRST_PARTY_APP_IDS:
        errors.append("freeze firstPartyApps does not contain the exact required app set")
    profiles = value.get("contentFormatProfiles") if isinstance(value.get("contentFormatProfiles"), list) else []
    profile_ids = [row.get("profileId") for row in profiles if isinstance(row, dict)]
    if profile_ids != list(CONTENT_PROFILE_IDS):
        errors.append("freeze contentFormatProfiles is not in the authoritative profile order")
    limitations = value.get("limitationsAndPolicy") if isinstance(value.get("limitationsAndPolicy"), dict) else {}
    allowed = limitations.get("allowedLimitations") if isinstance(limitations.get("allowedLimitations"), list) else []
    if limitations.get("allowedLimitationCount") != len(allowed):
        errors.append("freeze allowed limitation count does not match its records")
    if limitations.get("allowedLimitationsDigest") != semantic_digest(allowed):
        errors.append("freeze allowed limitation digest does not match its records")
    return errors


def _exception_target_is_non_waivable(section: Any, item: Any) -> bool:
    return isinstance(section, str) and isinstance(item, str) and item in (
        NON_WAIVABLE_EXCEPTION_TARGETS.get(section) or frozenset()
    )


def _non_waivable_change_reason(
    section: str,
    item: str,
    before: Any,
    after: Any,
) -> str | None:
    """Classify forbidden changes from frozen structure, never exception prose."""

    if _exception_target_is_non_waivable(section, item):
        return f"{section}.{item} is a non-waivable freeze invariant"
    if section == "stableCatalog" and item == "keyRotationStatus":
        if before != after and after != {"status": "complete", "compromised": False}:
            return "stableCatalog.keyRotationStatus would leave signing identity unsafe"
    if section == "limitationsAndPolicy" and item in {
        "betaOnlyLimitationCount",
        "disallowedLimitationCount",
    }:
        if before != after and after != 0:
            return f"limitationsAndPolicy.{item} would leave a non-waivable limitation"
    if section == "firstPartyApps" and isinstance(before, dict) and isinstance(after, dict):
        unsafe_changes = (
            before.get("channel") != after.get("channel") and after.get("channel") != "stable",
            before.get("apiCompatibilityResult") != after.get("apiCompatibilityResult")
            and after.get("apiCompatibilityResult") != "pass",
            before.get("appSigningKeyId") != after.get("appSigningKeyId")
            and not after.get("appSigningKeyId"),
            before.get("reviewerKeyId") != after.get("reviewerKeyId")
            and not after.get("reviewerKeyId"),
        )
        if any(unsafe_changes):
            return f"firstPartyApps.{item} would leave a non-waivable app invariant failing"
    return None


def validate_exception_collection(
    value: Any,
    release_id: str,
    build_version: str,
    now: Any,
) -> tuple[list[dict[str, Any]], list[str]]:
    """Validate authorized, expiring freeze-exception records without applying them as waivers."""

    if value is None:
        return [], []
    schema_errors = validate_schema(value, FREEZE_EXCEPTIONS_SCHEMA)
    errors = [f"freeze exception schema: {error}" for error in schema_errors]
    if not isinstance(value, dict):
        return [], errors
    if value.get("schemaVersion") != 1 or value.get("kind") != FREEZE_EXCEPTIONS_KIND:
        errors.append("freeze exception collection schemaVersion or kind is invalid")
    if value.get("authorizationRole") != "stable-release-manager":
        errors.append("freeze exception collection is under-authorized")
    redaction = value.get("redaction") if isinstance(value.get("redaction"), dict) else {}
    if redaction.get("status") != "pass" or redaction.get("findingCount") != 0 or redaction.get("findings") != []:
        errors.append("freeze exception collection redaction did not pass")
    records = value.get("exceptions")
    if not isinstance(records, list):
        return [], [*errors, "freeze exception records must be an array"]
    accepted: list[dict[str, Any]] = []
    seen: set[str] = set()
    for index, record in enumerate(records):
        prefix = f"exceptions[{index}]"
        error_count = len(errors)
        if not isinstance(record, dict):
            errors.append(f"{prefix} must be an object")
            continue
        required = {
            "exceptionId",
            "releaseId",
            "buildVersion",
            "affectedSection",
            "affectedItem",
            "beforeDigest",
            "afterDigest",
            "reason",
            "issueKind",
            "issueReference",
            "owner",
            "approver",
            "createdAt",
            "expiresAt",
            "requiredRerunScope",
            "finalVerificationResult",
        }
        if set(record) != required:
            errors.append(f"{prefix} fields are malformed")
            continue
        placeholders = placeholder_findings(record)
        if placeholders:
            errors.append(
                f"{prefix} contains production placeholder metadata at "
                + ", ".join(placeholders)
            )
        exception_id = record.get("exceptionId")
        if not isinstance(exception_id, str) or not exception_id or exception_id in seen:
            errors.append(f"{prefix}.exceptionId is missing or duplicated")
        seen.add(str(exception_id))
        if record.get("releaseId") != release_id or record.get("buildVersion") != build_version:
            errors.append(f"{prefix} does not match the candidate")
        if record.get("affectedSection") not in EXCEPTION_TARGET_SECTIONS:
            errors.append(f"{prefix}.affectedSection is invalid")
        for key in ("beforeDigest", "afterDigest"):
            if DIGEST_RE.fullmatch(str(record.get(key, ""))) is None:
                errors.append(f"{prefix}.{key} is malformed")
        for key in ("affectedItem", "reason", "issueReference", "owner", "approver"):
            if not isinstance(record.get(key), str) or not record[key].strip():
                errors.append(f"{prefix}.{key} must be non-empty")
        created = parse_timestamp(record.get("createdAt"))
        expires = parse_timestamp(record.get("expiresAt"))
        if created is None or expires is None or created >= expires or created > now or expires < now:
            errors.append(f"{prefix} timestamps are malformed, expired, or reversed")
        scope = record.get("requiredRerunScope")
        if not isinstance(scope, list) or not scope or not all(isinstance(item, str) and item for item in scope):
            errors.append(f"{prefix}.requiredRerunScope is malformed")
        elif not {
            "freeze-generation",
            "packaging",
            "stable-rc-final-gates",
        }.issubset(set(scope)):
            errors.append(f"{prefix}.requiredRerunScope omits mandatory final reruns")
        if record.get("issueKind") not in {"blocker", "security"}:
            errors.append(f"{prefix}.issueKind is invalid")
        if record.get("beforeDigest") == record.get("afterDigest"):
            errors.append(f"{prefix} does not describe a digest change")
        if record.get("finalVerificationResult") != "pass":
            errors.append(f"{prefix}.finalVerificationResult is not pass")
        if _exception_target_is_non_waivable(
            record.get("affectedSection"),
            record.get("affectedItem"),
        ):
            errors.append(f"{prefix} targets a non-waivable release blocker")
        if len(errors) == error_count:
            accepted.append(copy.deepcopy(record))
    return ([], errors) if errors else (accepted, [])


def _accepted_exception_items(value: Any) -> dict[str, dict[str, Any]]:
    """Index immutable accepted-exception audit records by their stable identifier."""

    if not isinstance(value, list):
        raise ValueError("freeze section acceptedFreezeExceptions must be an array")
    indexed: dict[str, dict[str, Any]] = {}
    for row in value:
        exception_id = row.get("exceptionId") if isinstance(row, dict) else None
        if not isinstance(exception_id, str) or not exception_id or exception_id in indexed:
            raise ValueError(
                "freeze section acceptedFreezeExceptions has a missing or duplicate exceptionId"
            )
        indexed[exception_id] = row
    return indexed


def merge_accepted_exception_history(
    previous: dict[str, Any] | None,
    current: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Carry immutable prior exception audit records into every regenerated freeze."""

    if previous is None:
        return copy.deepcopy(current)
    prior_items = _accepted_exception_items(previous.get("acceptedFreezeExceptions"))
    merged = [copy.deepcopy(row) for row in prior_items.values()]
    merged_items = {row["exceptionId"]: row for row in merged}
    for row in current:
        exception_id = row.get("exceptionId") if isinstance(row, dict) else None
        if not isinstance(exception_id, str) or not exception_id:
            raise ValueError("current freeze exception has a missing exceptionId")
        prior = merged_items.get(exception_id)
        if prior is not None:
            if prior != row:
                raise ValueError(
                    f"accepted freeze exception {exception_id} conflicts with its audit history"
                )
            continue
        copied = copy.deepcopy(row)
        merged.append(copied)
        merged_items[exception_id] = copied
    return merged


def compare_freezes(
    previous: dict[str, Any] | None,
    current: dict[str, Any],
    exceptions: list[dict[str, Any]],
) -> dict[str, Any]:
    """Compare complete semantic freeze sections and classify all post-freeze drift."""

    current_errors = validate_freeze_shape(current)
    if current_errors:
        return _drift_report("invalid-freeze", [], current_errors, [])
    if previous is None:
        if exceptions:
            return _drift_report(
                "invalid-freeze",
                [],
                ["freeze exceptions were supplied without a previous freeze"],
                [],
            )
        return _drift_report("no-drift", [], [], [])
    previous_errors = validate_freeze_shape(previous)
    if previous_errors:
        return _drift_report("invalid-freeze", [], previous_errors, [])
    previous_candidate = previous.get("candidate", {})
    current_candidate = current.get("candidate", {})
    identity_errors = [
        key
        for key in ("releaseId", "buildVersion")
        if previous_candidate.get(key) != current_candidate.get(key)
    ]
    if identity_errors:
        return _drift_report(
            "invalid-freeze",
            [],
            ["candidate identity mismatch: " + ", ".join(identity_errors)],
            [],
        )
    section_changes: list[dict[str, Any]] = []
    try:
        for section in EXCEPTION_TARGET_SECTIONS:
            before_items = _freeze_section_items(section, previous.get(section))
            after_items = _freeze_section_items(section, current.get(section))
            for item in sorted(set(before_items) | set(after_items)):
                before_digest = semantic_digest(before_items.get(item))
                after_digest = semantic_digest(after_items.get(item))
                if before_digest == after_digest:
                    continue
                change = {
                    "section": section,
                    "item": item,
                    "beforeDigest": before_digest,
                    "afterDigest": after_digest,
                }
                non_waivable_reason = _non_waivable_change_reason(
                    section,
                    item,
                    before_items.get(item),
                    after_items.get(item),
                )
                if non_waivable_reason is not None:
                    change["nonWaivableReason"] = non_waivable_reason
                section_changes.append(change)
        previous_exception_items = _accepted_exception_items(
            previous.get("acceptedFreezeExceptions")
        )
        current_exception_items = _accepted_exception_items(
            current.get("acceptedFreezeExceptions")
        )
    except ValueError as exc:
        return _drift_report("invalid-freeze", [], [str(exc)], [])
    audit_changes: list[dict[str, Any]] = []
    for exception_id in sorted(set(previous_exception_items) | set(current_exception_items)):
        before = previous_exception_items.get(exception_id)
        after = current_exception_items.get(exception_id)
        before_digest = semantic_digest(before)
        after_digest = semantic_digest(after)
        if before_digest != after_digest:
            audit_changes.append(
                {
                    "section": "acceptedFreezeExceptions",
                    "item": exception_id,
                    "beforeDigest": before_digest,
                    "afterDigest": after_digest,
                }
            )
    changes = [*section_changes, *audit_changes]
    if not section_changes and exceptions:
        return _drift_report(
            "invalid-freeze",
            changes,
            ["freeze exceptions were supplied but no freeze content changed"],
            [],
        )
    if not changes:
        return _drift_report("no-drift", [], [], [])
    approved: list[dict[str, Any]] = []
    unapproved: list[dict[str, Any]] = []
    used_exception_ids: set[str] = set()
    forbidden_exception_ids: set[str] = set()
    for change in section_changes:
        match = next(
            (
                record
                for record in exceptions
                if record.get("affectedSection") == change["section"]
                and record.get("affectedItem") == change["item"]
                and record.get("beforeDigest") == change["beforeDigest"]
                and record.get("afterDigest") == change["afterDigest"]
            ),
            None,
        )
        if "nonWaivableReason" in change:
            unapproved.append(change)
            if match is not None:
                exception_id = str(match.get("exceptionId"))
                forbidden_exception_ids.add(exception_id)
                used_exception_ids.add(exception_id)
        elif match is None:
            unapproved.append(change)
        else:
            approved.append({**change, "exceptionId": match.get("exceptionId")})
            used_exception_ids.add(str(match.get("exceptionId")))
    for change in audit_changes:
        exception_id = change["item"]
        current_record = current_exception_items.get(exception_id)
        active_record = next(
            (
                record
                for record in exceptions
                if record.get("exceptionId") == exception_id and record == current_record
            ),
            None,
        )
        is_new_matched_record = (
            exception_id not in previous_exception_items
            and active_record is not None
            and exception_id in used_exception_ids
        )
        if is_new_matched_record:
            approved.append({**change, "exceptionId": exception_id})
        else:
            unapproved.append(change)
    if forbidden_exception_ids:
        return _drift_report(
            "invalid-freeze",
            changes,
            [
                "freeze exceptions target non-waivable changes: "
                + ", ".join(sorted(forbidden_exception_ids))
            ],
            approved,
            unapproved,
        )
    unmatched = [
        str(record.get("exceptionId"))
        for record in exceptions
        if str(record.get("exceptionId")) not in used_exception_ids
    ]
    if unmatched:
        return _drift_report(
            "invalid-freeze",
            changes,
            ["unmatched freeze exception records: " + ", ".join(sorted(unmatched))],
            approved,
            unapproved,
        )
    status = "unapproved-drift" if unapproved else "approved-freeze-exception"
    return _drift_report(status, changes, [], approved, unapproved)


def _freeze_section_items(section: str, value: Any) -> dict[str, Any]:
    """Index one freeze section into the narrow items authorized by exception records."""

    identifier_key = {
        "firstPartyApps": "appId",
        "contentFormatProfiles": "profileId",
    }.get(section)
    if identifier_key is None:
        if not isinstance(value, dict):
            raise ValueError(f"freeze section {section} must be an object")
        return {str(key): child for key, child in value.items()}
    if not isinstance(value, list):
        raise ValueError(f"freeze section {section} must be an array")
    indexed: dict[str, Any] = {}
    for row in value:
        identifier = row.get(identifier_key) if isinstance(row, dict) else None
        if not isinstance(identifier, str) or not identifier or identifier in indexed:
            raise ValueError(f"freeze section {section} has a missing or duplicate {identifier_key}")
        indexed[identifier] = row
    return indexed


def _drift_report(
    status: str,
    changes: list[dict[str, Any]],
    errors: list[str],
    approved: list[dict[str, Any]],
    unapproved: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    return {
        "schemaVersion": 1,
        "kind": "stable-1.0-rc-freeze-drift",
        "status": status,
        "driftCount": len(changes),
        "changes": changes,
        "approvedChanges": approved,
        "unapprovedChanges": unapproved or [],
        "errors": errors,
    }


def _integer(value: Any) -> int | None:
    try:
        parsed = int(str(value))
    except (TypeError, ValueError):
        return None
    return parsed if parsed >= 0 else None
